"""Storage protocol — typing.Protocol defining the contract both Storage and SurrealStorage satisfy."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol, runtime_checkable

from .models import (
    ConsolidationLogEntry,
    Memory,
    MemoryVersion,
    Relationship,
)


@runtime_checkable
class StorageProtocol(Protocol):
    """Contract for synaptra storage backends."""

    # --- Memory CRUD ---

    def insert_memory(self, memory: Memory, embedding: list[float] | None = None) -> None: ...

    def get_memory(self, memory_id: str) -> Memory | None: ...

    def update_memory_fields(self, memory_id: str, **fields: Any) -> None: ...

    def update_embedding(self, memory_id: str, embedding: list[float]) -> None: ...

    def delete_memory(self, memory_id: str) -> None: ...

    def list_memories(
        self,
        search: str | None = None,
        memory_type: str | None = None,
        state: str | None = None,
        tags: list[str] | None = None,
        time_range: tuple[datetime, datetime] | None = None,
        importance_min: float | None = None,
        importance_max: float | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[Memory]: ...

    def get_all_active_memories(self) -> list[Memory]: ...

    def get_memories_by_ids(self, ids: list[str]) -> list[Memory]: ...

    def get_recent_active_ids(
        self,
        limit: int,
        type_filter: str | None = None,
        time_range: tuple[datetime, datetime] | None = None,
    ) -> list[tuple[str, datetime]]: ...

    # --- Search ---

    def fts_search(self, query: str, state: str = "active", limit: int = 30) -> list[tuple[str, float]]: ...

    def vector_search(self, embedding: list[float], state: str = "active", top_k: int = 30) -> list[tuple[str, float]]: ...

    def vector_search_for_memory(self, memory_id: str, top_k: int = 10) -> list[tuple[str, float]]: ...

    # --- Versions ---

    def insert_version(self, version: MemoryVersion) -> None: ...

    def get_versions(self, memory_id: str) -> list[MemoryVersion]: ...

    # --- Relationships ---

    def insert_relationship(self, rel: Relationship) -> None: ...

    def delete_relationship(self, source_id: str, target_id: str, rel_type: str) -> bool: ...

    def get_relationships_for(self, memory_id: str, rel_types: list[str] | None = None) -> list[Relationship]: ...

    def get_outgoing_relationships(self, memory_id: str) -> list[Relationship]: ...

    def get_incoming_relationships(self, memory_id: str, rel_type: str | None = None) -> list[Relationship]: ...

    def get_neighbors(self, memory_id: str, active_only: bool = True) -> list[tuple[str, Relationship]]: ...

    def delete_auto_links(self, memory_id: str) -> None: ...

    def bulk_update_stability(self, updates: list[tuple[float, str]]) -> None: ...

    def has_incoming_supersedes(self, memory_id: str) -> bool: ...

    def get_contradictions_for(self, memory_id: str) -> list[tuple[str, str, float]]: ...

    # --- Consolidation Log ---

    def insert_consolidation_log(self, entry: ConsolidationLogEntry) -> None: ...

    def get_last_consolidation(self) -> dict | None: ...

    def get_consolidation_summary(self) -> dict: ...

    # --- Config ---

    def get_config(self, key: str) -> Any | None: ...

    def set_config(self, key: str, value: Any) -> None: ...

    def get_all_config(self) -> dict[str, Any]: ...

    # --- Stats ---

    def get_counts_by_type(self) -> dict[str, int]: ...

    def get_counts_by_state(self) -> dict[str, int]: ...

    def get_total_memory_count(self) -> int: ...

    def get_db_size(self) -> int: ...

    # --- Health ---

    def get_counts_by_type_and_state(self) -> dict[tuple[str, str], int]: ...

    def get_active_memories_for_decay(self) -> list[dict[str, Any]]: ...

    def get_orphan_untagged(self) -> tuple[list[dict[str, Any]], int]: ...

    def get_orphan_unconnected(self) -> tuple[list[dict[str, Any]], int]: ...

    def get_tag_frequencies(self) -> list[list[str]]: ...

    def get_health_consolidation_summary(self) -> dict[str, Any] | None: ...

    # --- Lifecycle ---

    def close(self) -> None: ...
